#!/usr/bin/env bash
# gen-claude-md.sh <project_dir>
# Stage 3 完成后生成项目 CLAUDE.md，为所有后续 agent 提供一致的上下文
# harness 原则：确定性信息由脚本写入，不让每个 agent 重复推断
set -euo pipefail

PROJECT_DIR="${1:-$PWD}"
PROJECT_NAME=$(basename "$PROJECT_DIR")

TDD=$(ls "$PROJECT_DIR"/docs/tdd-*.md 2>/dev/null | head -1 || echo "")
PRD=$(ls "$PROJECT_DIR"/docs/prd-*.md 2>/dev/null | head -1 || echo "")
OUTPUT="$PROJECT_DIR/CLAUDE.md"

cat > "$OUTPUT" << MD
# $PROJECT_NAME — Project Context

> Auto-generated by ship workflow. All agents read this before writing code.
> For full design: see docs/prd-*.md (product) and docs/tdd-*.md (technical).

## Tech Stack

| Layer | Technology |
|-------|-----------|
| Backend | Elysia.js 1.x + Drizzle ORM + bun:sqlite |
| Frontend | React 18 + Vite + TanStack Query + React Router + Tailwind CSS 4 |
| Monorepo | bun workspaces (apps/server + apps/web) |
| Testing | bun:test (unit/api) + Playwright (e2e) |

## Directory Layout

\`\`\`
apps/
  server/src/
    index.ts          # Elysia app entry, export type App
    db/
      schema.ts       # Drizzle table definitions
      client.ts       # DB singleton + auto-migrate
    routes/           # One file per resource group
  web/src/
    routes/           # One component per page/route
    components/       # Shared components
    lib/
      api.ts          # fetchApi helper
      constants.ts    # Categories, types, etc.
      utils.ts        # formatAmount, formatDate, etc.
tests/
  unit/               # Pure function tests, always green
  api/                # In-memory SQLite integration tests
  e2e/                # Playwright, one spec per user story
\`\`\`

## API Conventions

- Base prefix: \`/api\`
- Error format: \`{ "error": "human message", "code": "SCREAMING_SNAKE_CASE" }\`
- HTTP status: 201 create · 204 delete · 400 validation · 404 not found · 409 conflict

## Code Conventions

**Backend**
- All inputs validated via Elysia \`t.Object()\` schema before handler runs
- Drizzle ORM for all DB operations — no raw SQL strings
- Global \`.onError()\` handler in index.ts catches unhandled exceptions

**Frontend**
- API calls: use \`fetchApi\` helper in \`lib/api.ts\` — not Eden Treaty, not raw fetch scattered across files
- Forms: always \`noValidate\`, disable submit while \`mutation.isPending\`
- List items: add \`data-testid\` for Playwright selectors

**Tests**
- API tests: each describe block creates its own in-memory DB — no shared state
- E2E seeding: use \`page.request.post()\` not UI forms
- \`toHaveURL()\` regex: no \`^\` anchor (matches full URL including scheme+host)
MD

echo "[gen-claude-md] ✅ Generated $OUTPUT"
